name: Clone and Build CloudAddr

on:
  push:

  schedule:
    - cron: '0 12 * * *'
    
  workflow_dispatch:

jobs:
  UpdateGeneratedData:
  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Clone CloudAddr
      uses: actions/checkout@v3
      with:
        repository: hyperxpro/CloudAddr
        ref: main
        path: CloudAddr/

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 17
        architecture: x64

    - name: Build and Run CloudAddr Generator
      run: cd CloudAddr && chmod +x ./mvnw && ./mvnw clean install -ntp -B && ./mvnw exec:java -Dexec.mainClass="com.aayushatharva.cloudaddr.generator.Main" -pl generator -ntp -B

    - name: Copy Generated Data Folder
      run: cp -r CloudAddr/data .

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.0.0
      with:
        default_author: github_actions
        message: "Update Database - ${{{ steps.date.outputs.date }}}"
        add: 'data'
